# Generated by Django 5.1.15 on 2026-07-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('approved_for_subscribe', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('UNDER_SUBSCRIPTION', 'Under Subscription'), ('SUBSCRIBED', 'Subscribed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=40)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
