# Generated by Django 5.1.15 on 2026-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_searchsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="selected_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="selected_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
