# Generated by Django 5.1.15 on 2026-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_searchsession_selected_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="init_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="init_order",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="selected_bpp_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="selected_bpp_uri",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
