# Generated by Django 5.1.15 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_searchsession_init_error_searchsession_init_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="confirmed_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="confirmed_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
