# Generated by Django 5.1.15 on 2026-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_searchsession_confirmed_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="cancelled_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="cancelled_order",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="status_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="status_order",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="tracking",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="tracking_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="updated_error",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchsession",
            name="updated_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
