# Generated by Django 5.1.15 on 2026-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_searchsession_cancelled_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="client_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
