# Generated by Django 5.1.15 on 2026-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_searchsession_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='rating_error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='rating_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='support_error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='support_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
