# Generated by Django 6.0.7 on 2026-07-14 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber_id", models.CharField(db_index=True, max_length=255)),
                ("subscriber_url", models.URLField(max_length=500)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("buyerApp", "Buyer App"),
                            ("sellerApp", "Seller App"),
                        ],
                        max_length=20,
                    ),
                ),
                ("domain", models.CharField(max_length=100)),
                ("country", models.CharField(default="IND", max_length=10)),
                ("city_code", models.JSONField(blank=True, default=list)),
                ("unique_key_id", models.CharField(max_length=255)),
                ("signing_public_key", models.TextField()),
                ("encryption_public_key", models.TextField()),
                ("key_valid_from", models.DateTimeField()),
                ("key_valid_until", models.DateTimeField()),
                ("callback_url", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("UNDER_SUBSCRIPTION", "Under Subscription"),
                            ("SUBSCRIBED", "Subscribed"),
                            ("INVALID_SSL", "Invalid SSL"),
                            ("UNSUBSCRIBED", "Unsubscribed"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscriber_id"], name="core_partic_subscri_4d07fb_idx"
                    ),
                    models.Index(
                        fields=["domain"], name="core_partic_domain_71c607_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscriber_id", "domain", "participant_type"),
                        name="unique_subscriber_domain_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plaintext_challenge", models.CharField(max_length=255)),
                ("encrypted_challenge", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="core.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(max_length=50)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
