# Generated by Django 5.1.15 on 2026-07-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.CharField(choices=[('buyerApp', 'Buyer App'), ('sellerApp', 'Seller App'), ('gateway', 'Gateway')], max_length=20),
        ),
    ]
