# Generated by Django 5.1.15 on 2026-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='domain_code',
            field=models.CharField(default='ONDC:RET13', max_length=100),
        ),
    ]
