# Generated by Django 5.1.15 on 2026-07-18 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_ref", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("short_desc", models.CharField(blank=True, max_length=255)),
                ("long_desc", models.TextField(blank=True)),
                ("category_id", models.CharField(blank=True, max_length=100)),
                ("rateable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvailabilityCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.DurationField(help_text="Recurrence interval, e.g. 1 day."),
                ),
                ("range_start", models.DateTimeField()),
                ("range_end", models.DateTimeField()),
                (
                    "days",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated weekday tokens (MON..SUN). Blank means every day.",
                        max_length=50,
                    ),
                ),
                (
                    "times",
                    models.JSONField(
                        default=list,
                        help_text='Time-of-day anchors, e.g. ["09:00", "14:00"].',
                    ),
                ),
                (
                    "holidays",
                    models.JSONField(
                        default=list, help_text='Excluded dates, e.g. ["2026-12-25"].'
                    ),
                ),
                (
                    "slot_duration",
                    models.DurationField(help_text="Length of each generated slot."),
                ),
                ("slot_capacity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_calendars",
                        to="inventory_core.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("capacity_total", models.PositiveIntegerField()),
                ("capacity_remaining", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("HELD", "Held"),
                            ("BOOKED", "Booked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="inventory_core.resource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource", "start_time", "end_time"],
                        name="slot_resource_time_idx",
                    ),
                    models.Index(fields=["status"], name="slot_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="slot_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capacity_remaining__lte", models.F("capacity_total"))
                        ),
                        name="slot_capacity_remaining_lte_total",
                    ),
                ],
            },
        ),
    ]
