# Generated by Django 5.1.15 on 2026-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity_remaining__gte", 0)),
                name="slot_capacity_remaining_gte_zero",
            ),
        ),
    ]
