# Generated by Django 5.1.15 on 2026-07-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_core", "0003_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
