# Generated by Django 5.1.15 on 2026-07-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_core", "0004_processedevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="domain_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="domain_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
