# Generated by Django 5.1.15 on 2026-07-20 12:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_core", "0005_booking_domain_data_resource_domain_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="price_currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="resource",
            name="price_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
