# Generated by Django 5.1.15 on 2026-07-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0006_resource_price_currency_resource_price_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id_text', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='inventory_core.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
