# Generated by Django 5.1.15 on 2026-07-28 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0007_bookingauditlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id_text', models.CharField(db_index=True, max_length=64)),
                ('rating_category', models.CharField(choices=[('Item', 'Item'), ('Order', 'Order'), ('Fulfillment', 'Fulfillment'), ('Provider', 'Provider'), ('Agent', 'Agent'), ('Support', 'Support')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('correlation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='inventory_core.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
