# Generated by Django 5.1.15 on 2026-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'rating_category'), name='unique_rating_per_booking_category'),
        ),
    ]
