# Generated by Django 5.1.15 on 2026-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_core",
            "0009_resource_average_rating_resource_rating_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="confirmed_total_currency",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="confirmed_total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
