# Generated by Django 5.1.15 on 2026-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_core", "0010_booking_confirmed_total_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
